### PR TITLE
Proposed-TemplatedEvents

### PR DESCRIPTION
**Pull request by MakoEnergy**
A significant change from the previous event system where a completely custom interface can have events dispatched to it, even selectively choosing which method to dispatch to.  Making it possible to have a method per event instead of a catch-all event info class (if one desires).

This also enables the use of slimmed down event dispatch for systems that don't need the extra bulk of the previous system.  The old system was well suited for event dispatch across multiple different subsystems, but wasn't well suited to dispatch within the same system due to the bulk.  In most cases, that bulk is the bindings to help track subscriber/publisher lifetime.  The use of bindings is now optional.

### CODE REVIEW

**Comment by MakoEnergy** [comment]
The new containers to review:
https://github.com/BlackToppStudios/Mezzanine/blob/Proposed-TemplatedEvents/Mezzanine/src/managedarray.h
https://github.com/BlackToppStudios/Mezzanine/blob/Proposed-TemplatedEvents/Mezzanine/src/sortedmanagedarray.h

The tests for them (I pretty much blatently copied the SortedVector tests):
https://github.com/BlackToppStudios/Mezzanine/blob/Proposed-TemplatedEvents/UnitTests/tests/managedarraytests.h
https://github.com/BlackToppStudios/Mezzanine/blob/Proposed-TemplatedEvents/UnitTests/tests/sortedmanagedarraytests.h

**Comment by Sqeaky** [comment]
This looks really good. I have only minor points to raise.

On line 188 of the tests the "void" was omitted from this line "void operator()(const SortedManagedArray<String,6>& ToReport)"

Any reason that wasn't just a lambda?

    auto TestReporter = [](){ the code };

Should the add method be "insert" to be more like the std sorted containers?

I like how you got the comparator function as a template parameter, no runtime cost like a more naive implementation might have had.

The template params on the ManagedArray are clear and self descriptive, but those on the SortedManagedArray are single letters.

The doxygen docs for the tparams on the SortedManagedArray

Since most arrays are under capacity and the used space is checked often does it make sense from a caching standpoint to put it before the storage space? This can be put off until later, when we start carrying about the perf of this component.

**Comment by MakoEnergy** [comment]
The TestReporter thing was just to help me debug why that test was failing.  I meant to remove it prior to pushing and forgot.  But you are right, I should have made it a lamda.

I think insert means that it's being placed with intent, add is sufficient since the algorithm is what is doing the placing, not the user.

I'm not sure about the placement of the member "UsedSpace".  With small arrays it shouldn't matter.  With larger arrays...it'll be a problem regardless I would think.  Wouldn't the compiler also optimize the order in some cases?

**Comment by Sqeaky** [comment]
in Mezzanine/libincludes/common/sdlsrc/SDL/CMakeLists.txt  on line  1347 it appears there is a tab instead of spaces.

**Comment by Sqeaky** [comment]
Copyright date in binaryfind.h was changed and still says 2017.

**Comment by Sqeaky** [comment]
In the docs for the Event system in Mezzanine/src/eventpublisher.h around line 60 - 70 consider adding some examples of what a "system" or "subsystem" are to make this less abstract for someone reading reading it.

I think there is a chance that around lines 70 - 100 you could get odd formatting depending on Doxygen version. Consider using @Section or @SubSection these allow titles and linking to them with @ref. You could even make a single bulleted list if you really do want one, then use @ref to link to each section, but I think this would be overkill.

On line 113 The grammar in this sentence seems off "Subscribers have only two requirements mandated by the system, have an ID class defined and a method to get that instances ID."

**Pull request merged**
