### PR TITLE
Proposed-ECSRename

### PR DESCRIPTION
**Pull request by MakoEnergy**
Renamed WorldObject to WorldEntity throughout the repo as outlined in issue #155.

### CODE REVIEW

**Comment by Sqeaky** [comment]
In Catch/CMakeLists.txt there are some ^M on the end of lines you changed.

**Comment by Sqeaky** [comment]
A line with this comment /* Why the hell is this line important? */ was changed and the question was neither removed nor changed. Should something be done about that?

**Comment by Sqeaky** [comment]
A line with this comment /* Why the hell is this line important? */ was changed and the question was neither removed nor changed. Should something be done about that?

**Comment by Sqeaky** [comment]
That was fast, I wasn't done yet, I got distracted with people in real....

I am pulling and I will finish the whole review.

**Comment by Sqeaky** [comment]
I see trailing whitespace in Mezzanine/libincludes/common/sdlsrc/CMakeLists.txt, but I really like how you sorted the advanced options. It is simple and clearly conveys hierarchy.

**Comment by Sqeaky** [comment]
More trailing whitespace in some of the patches  SDL_x11_modes.c.May.31.2017.patch and SDL_xinput.h.May.28.2017.patch

Wait... are these part of this PR, I did `git diff master` from the PR branch. is that right?

**Comment by Sqeaky** [comment]
OK, don't worry about that SDL stuff my master must be out of date. Using the github UI the clairty of the Rename is apparent. I am duing a test build and tests.

**Comment by Sqeaky** [comment]
I am getting complaint from cmake that I have not seen before:

```
The dependency target "Tclap" of target "Armadillo" does not exist.
This warning is for project developers.  Use -Wno-dev to suppress it.
```

and 

```
The dependency target "EntreLuaTclap" of target "EntreLua" does not exist.
This warning is for project developers.  Use -Wno-dev to suppress it
```

I also had to re-run swig which is entirely expected for a a rename, I just had the setting disabled for some reason. It did build fine and the tests ran the same as before.

**Comment by Sqeaky** [comment]
Do you want to fix the whitespace in the PR or should I just merge as is?

**Comment by MakoEnergy** [comment]
Those cmake complaints are nothing new for me.  Been there for a year or more.  They don't impact anything that I do atm.

Aside from the SDL stuff you mentioned (which isn't a part of this PR), what other whitespace issues are there?

**Comment by MakoEnergy** [comment]
I've looked at the CMakeLists.txt in a hex editor, and I only see a CRLF at the end of the line (as there should be).  Git should be removing those on upload.  So I'm not sure what you are seeing.

**Comment by Sqeaky** [comment]
Whatever those Control M's are they aren't breaking the build. Merging.

**Pull request merged**
