### PR TITLE
Proposed-EventRefactor

### PR DESCRIPTION
**Pull request by MakoEnergy**
This is a series of changes designed to remove the old event system entirely.  Replacing existing functionality with the new event system where possible.

### CODE REVIEW

**Comment by Sqeaky** [comment]
I think we talked about void GraphicsManager::PumpInternalEvents(), but I think it can be sanely shortened without additional performance overhead.

Before shortening, I think you should replace the C style array with and std::array. It makes it harder to write complex bugs when refactoring. If I went in and changed the size of the array, I would need to know that the 16 was used in both places (presuming it is only two), the std::array::size would adjust automatically.

I see a few ways to refactor the major loop pumping cleanly. You could make a small series of functions that are either private or in an anonymous namespace, that dispatch one type of SDL event. Since these functions don't need to return anything, each case could be shortened to a single line.

**Comment by Sqeaky** [comment]
If the switch/case still dominates too much of the function it could be pulled out too, and just one entry could be passed to a function that dispatches just a single SDL_Event.

**Comment by Sqeaky** [comment]
Viewport::IsWithinBounds, could gain an assert verifying the bounds of the types. In debug builds it should blow up on overflows if they can exist. I know that the range of a real is huge, but it is possible to make an x windows display with arbitrary offset so it could push Reals up into the range where Real's epsilon is worse than 1.0.

**Comment by Sqeaky** [comment]
in inputenumerations.h InputCode::KEY_UNKNOWN uses a tab for spacing and this prevents it from lining up correctly on github.

**Comment by Sqeaky** [comment]
InputManager::PumpInternalEvents() should use an std::array instead of a c style array.

**Comment by MakoEnergy** [comment]
I fixed a couple of the items already.  I was about to add the assert to the Viewport class, however I realized at the last moment that I don't actually fully understand what you are suggesting.  That I check for num_limits::max()?  Or something else?

**Comment by Sqeaky** [comment]
It probably isn't a big deal and I will agree to to merging if you disagree, but here is the full explanation of what I meant earlier. For sane values there are probably no problems. But as values move away from 0 the real loses precision, at some point it loses enough precision that it cannot represent every pixel. If the origin of a screen had to be 0,0 like any other sane system than anything less than a long chain of 8k monitors could have enough pixels for this to matter. But in some x windowing systems someone mucking around with the x config can start a viewport off with arbitrary coordinates and put it neat the limits of an int. If offset from 0,0 is far enough it go be beyond the precision of a Real to represent a pixel uniquely.

To detect this an assert could cast the value back to an int and compare to the input for equality.

**Comment by Sqeaky** [comment]
Your breaks in the new version of GraphicsManager::PumpInternalEvents() don't all line up. This is of course perfectly acceptable, but if is the kind of thing I cannot see you wanting to leave unfixed.

**Comment by Sqeaky** [comment]
could you explain Keyboard::GetDeviceID()?

**Comment by Sqeaky** [comment]
There are giant switch/cases in MetaCode::CreateMetaCodes and InputManager::PumpInternalEvents() that are concerning, but if you say they cannot be factored now I would like to take a stab at it when the Jagati refactor catches up with these functions.

**Comment by Sqeaky** [comment]
What is going on with UIManager::HandlePostFocusKeyboardInput(const Input::MetaCode& Code) and UIManager::HandlePostFocusMouseInput(const Input::MetaCode& Code)? are these just dead input.

**Comment by Sqeaky** [comment]
We need to ditch ConvertToString, now that there is an std::to_string. Or at least delegate in cases where we where using stringstreams for trivial conversions.

**Comment by Sqeaky** [comment]
Thank goodness there were like 3000 lines of removals at the end or this wasn't getting done tonight, I just ran out of monster.

**Comment by MakoEnergy** [comment]
1) You explained the nature of the problem alright, I just didn't know how to go about addressing it.  That sounds like a reasonable approach, although I'm not sure it's necessary.  But, whatever.  I can throw it in.

2) If you are referring to the 3 breaks after the methods that need to take the internal event itself to handle them...then sadly that is intentional.  I was shortening the lines to keep them under 120 characters where I could, and dealing with it where I couldn't.  120 is based on file width concerns you raised before.

3) Keyboard::GetDeviceID() ( as well as Mouse::GetDeviceID() ), return the max value representable by their types to indicate there isn't really a sensical ID there.  Systems have a mouse and a keyboard, even if multiples are plugged in you get just one using default api's.  The methods exist because it's on the Device interface, and I haven't removed it from the base class in case we want to add to the api to support multiple mice/keyboards in the future.

4) I might be able to refactor the MetaCode switch case.  I'm actually reviewing the InputManager to clean some stuff up now.  If an opportunity opens up I'll take it.

5) Those are currently just stubs for later updates.  At least, I think.  It's been so long since I've been in the UI system I'd have to look closely at them again to be sure.  But that isn't really a focus of this PR.

6) I'll add that to the Jagati conversion checklist.

7) Oh for fear!  You should restock.  Not for this PR, but just because.

**Comment by Sqeaky** [comment]
That was one can of monster for the PR, not my whole supply, what kind of slacker do you think I am?

**Pull request merged**
