### PR TITLE
Proposed-FlatMap

### PR DESCRIPTION
**Pull request by MakoEnergy**
Implementation of the FlatMap container class.

This PR also includes some other trivial fixes and improvements I spotted while implementing the FlatMap.  All FlatMap unit tests pass on the machine it was written on.  The FlatMap has 348 unit tests.

### CODE REVIEW

**Comment by Sqeaky** [comment]
Fixed Linux build. All new UnitTests pass.

**Comment by Sqeaky** [comment]
Should the deleted constructor be private on the comparator?

Consider spaces after commas in lists parameter lists with lots of dots and period such as `CompFunct(Left.first,Right.first)`.

Why have a lower_bound member function? I supposed why not also.

**Comment by MakoEnergy** [comment]
I wanted the FlatMap to be as much of a drop in replacement for the C++14 std::map as I could get.  It pretty much is exactly that (hence upper and lower bound members), plus the "contains" method found in C++20 and the non-const iterator overload of erase that was dropped in C++11 and re-added in C++17.

If the constructor is deleted, what does it's access specifier matter?

**Comment by Sqeaky** [comment]
> If the constructor is deleted, what does it's access specifier matter?

I don't have a good reason other than that people in C++ talks do it. I had been doing and I thought I saw you do it at least once before.

I was unaware of the lower_bound member function I thought it was just in std::algorithms

**Comment by MakoEnergy** [comment]
If I had to guess, it's an old habit?  Making them private was the old way to remove them.

**Comment by Sqeaky** [comment]
I get most of the maps.The planets, the moons, and some arbitrary numbers, but what gives with the aardvarks and zebras. I see that you are testing the specifics of lexicographical sorting which is important and often missed, but why pair that with ints? Are we counting Zoo animals?

Ok, I have no other real concerns. I am merging this.

**Comment by Sqeaky** [comment]
Oh, I redownloaded and all the FlatMap tests passed again.

**Pull request merged**
