### PR TITLE
Proposed-StaticAny

### PR DESCRIPTION
**Pull request by MakoEnergy**
The StaticAny is a simple single element type-erased container.  Ok...maybe not "simple".  It's meant to be used with other containers to allow them to store multiple types, but of course it doesn't need to be used that way.  It does store type information in the form of a function pointer allowing retrievals for the type erased data to be safe.

### CODE REVIEW

**Comment by Sqeaky** [comment]
StaticAny in the Mezzanine passes all unit tests on my Ubuntu 18.04 x 64.

I will finish reading the code next.

**Comment by Sqeaky** [comment]
StaticAny in the Mezzanine passes all unit tests on my Ubuntu 18.04 x 64.

**Comment by Sqeaky** [comment]
In CMake MIR_LIB and X_INCLUDEDIR are not marked as advanced and show in ungrouped entries.

**Comment by Sqeaky** [comment]
In CMake MIR_LIB and X_INCLUDEDIR are not marked as advanced and show in ungrouped entries.

**Comment by Sqeaky** [comment]
This builds and the tests are as good as there ever were. I don't see any new tests, but I am not done looking yet.

**Comment by MakoEnergy** [comment]
I double checked and you should be seeing new UnitTests.  Should be named "StaticAny".

**Comment by Sqeaky** [comment]
I am looking at this again.

I figure out why the unit tests weren't showing up, A mistake on my part doing a fresh build.

**Comment by MakoEnergy** [comment]
Those files haven't been touched in this PR and have been included in the repo for over a year now.  A quick glance at even files like mezzanine.h that might be intruding don't show anything obvious for why that would occur.

**Comment by MakoEnergy** [comment]
So, I'm looking at the line numbers on github and the line numbers reported in your error messages and they don't like up at all.  "SimpleVersion" is only mentioned once in "httpmessage.h" yet you are getting errors referencing it on multiple lines in that file.  Some of those lines are lines that are just comments.  Something seems very borked about your copy.

**Comment by Sqeaky** [comment]
I reset and check my copy up from git again. I also erased my build
directory and recreated that fresh. What steps would you recommend I try?

-- Joseph Toppi
toppij@gmail.com
402-714-7539

**Comment by MakoEnergy** [comment]
Well...given the errors you showed, there are two possibilities.  Either you have the wrong version of the code, which would imply a git configuration error, or there is something being included that is messing with types and somehow line numbers which doesn't manifest on windows.  Personally...this screams git config error to me.  I have no idea how it got that way nor am I really sure how to fix aside from trying a completely fresh clone.

**Pull request merged**
