### PR TITLE
Proposed-EventRefactor

### PR DESCRIPTION
**Pull request by MakoEnergy**
A small series of overhauls to the core classes of our new Event system.  It is still incomplete but enough is done to be presented.  

I even included a mini-manual in the publisher header.

### CODE REVIEW

**Comment by Sqeaky** [comment]
In Catch/src/catchapp.cpp:313 why 0 and 0u like the other places?

I like the removal of new this part of catchapp, btw.

I am abou 1/3rd of the way through the diff, I will resume later.

**Comment by MakoEnergy** [comment]
The differences between 0 and 0u are left over from some experimentation.  Either will work and I'll probably change them to all 0.  

The removal of new was actually an unintended side effect.  You can't new them and throw them into a std::function, as I found out.  Has to be stack allocated.

**Comment by Sqeaky** [comment]
When redoing the foundation we need to abuse constexpr in the HashedString as much as possible. There is no reason to be computing hashes at runtime for strings like Widget::EventMouseEnter

**Comment by Sqeaky** [comment]
Since the Event is composed entirely of a HashedString it might make sense to store them all in a hash table or something (SortedVector?) and pass around the Hash instead of an Event::EventPtr. This looks good as it is, but if we decide to simplify further and dig for more performance that is something to consider.

**Comment by MakoEnergy** [comment]
Agreed completely on the constexpr.

Event is a base class.  If additional parameters are needed to express a given event (which is often the case) then the user is expected to derive from the Event base class and implement the additional parameters.

**Comment by Sqeaky** [comment]
in the Documentation at eventpublisher.h around 134 you should also that adding a subscriber could also interfere, because the things could move.

**Comment by Sqeaky** [comment]
We talked about it in person, but there are several places hash collisions could hurt this design. Seperating concerns can largely address this. Don't have functions that create or find, have one function creates or fails and another that finds or fails. The let people build policy on top of that. Then when a collision happens it can easily be sorted by game devs.

**Comment by Sqeaky** [comment]
In Mezzanine/src/eventpublisher.h on line 168 the EventCount could be more clear as EventCapacity, this word already has the meaning of the amount of space allocated, but not yet used.

**Comment by Sqeaky** [comment]
The NameHash on the EventSubscriberBinding should not be a hardcoded as an Int32, it should be HashedString::HashType and that needs to be created. This indicates deeper problems with the HashedString.

**Comment by Sqeaky** [comment]
I get that there is an implicit operator== on the EventSubscriberID, but with the amount of subtlety in that class being explicit with that might be a good idea.

**Comment by Sqeaky** [comment]
Consider using words like "subscription" when they are more descriptive. Perhaps EventSubscriberTable should be EventSubscribtionTable, because "subscription" implies a relationship that can make it easier for readers.

**Comment by Sqeaky** [comment]
We should add some ifdefs around the remarked out code in the HashedString to enable the entire comparisons when some debug flag is enabled or something.

**Comment by Sqeaky** [comment]
The constructor in src/statemachine.h on line 138 is not explicit. It seems like a bad idea to pass in implicitly constructed state machines when a string is passed.

**Pull request merged**
