### PR TITLE
Proposed-ECSID

### PR DESCRIPTION
**Pull request by MakoEnergy**
Created ID classes for Entity and Component.  Updated all relevant classes to use them.  Removed the requirement for a unique name on Entities.

### CODE REVIEW

**Comment by Sqeaky** [comment]
I am having some fairly serious issues building this. apparently there is no default constructor and SWIG really want there to be one. I know there is a way to have it skip that, but I am not sure how to approach that right now. I will look more tomorrow.

**Comment by MakoEnergy** [comment]
Strange.  I never encountered that.  The World class is also not something I touched in this PR, so it's behavior should be identical to before.  I don't see anything obvious that would suggest there is a new include path, either.

In case it matters (doubt it), I upgraded to SWIG 3.0.12 not too long ago.

**Comment by Sqeaky** [comment]
I will update swig and try again.

**Comment by Sqeaky** [comment]
I installed and built swig from source, no change. I figured out that the SWIG could not construct the type because it did not understand the child types correctly. Though I prefer the using= syntax in this instance swig simply didn't understand it. It now builds for me.

I have made minimal changes to allow @MakoEnergy to decide what he wants to do with this.

**Comment by MakoEnergy** [comment]
I find SWIGs lack of consistency....disturbing.

I didn't have any of these issues (as I've stated), but worse is that it's being picky about which "using" to complain about.  I've been transitioning to using them in more and more places.  Especially after I upgraded my version of SWIG (exactly that is why I upgraded, even).  But these lines in particular it takes issues with?  

I'll be in my angry dome.

**Comment by Sqeaky** [comment]
Did you build with Mezz_SWIG enabled? If not it simply does not run and old first might have built. I often test your PRs with and without it.

I agree swig is suboptimal, but it is the best at what it does. All the other tools require learning a complex and limited IDL (Interface defintion Language), they tend to be misrosoft or java only as well. SWIG scope and relative success are huge by comparison. Doesn't make shit like feel any better though.

**Comment by MakoEnergy** [comment]
I have Mezz_SWIG enabled constantly.  It needs to be given how often I change the API, or else it won't compile.

**Comment by MakoEnergy** [comment]
I decided to look it up to see what is going on, or if there is anything I can add to make intent clearer to SWIG.  Looks like SWIG is supposed to support type aliases out of the box: http://www.swig.org/Doc3.0/CPlusPlus11.html#CPlusPlus11_alias_templates

If you are trying to template the alias, then you need to give SWIG assistance.  Otherwise it should be fine.  Gonna try and dig deeper.

**Comment by Sqeaky** [comment]
I know we talked about this in person, but here is where I got the source: http://www.swig.org/download.html

Type aliases are partially supported. What I think is screwing with them is that they are nested classes which have historically been a pain point for SWIG and they have the same unqualified name and only differ in scope.

Out of curiosity what compiler and version are you using? I am using:
`
gcc version 6.3.0 20170406 (Ubuntu 6.3.0-12ubuntu2) 
`
To further check versions on SWIG, my current version is:

```
sqeaky@SleeperService:~/Code/Mezzanine$ swig -version

SWIG Version 3.0.12

Compiled with g++ [x86_64-pc-linux-gnu]

Configured options: +pcre

Please see http://www.swig.org for reporting bugs and further information
```

**Comment by MakoEnergy** [comment]
`gcc version 6.3.0 (x86_64-posix-seh-rev2, Built by MinGW-W64 project)`

`SWIG Version 3.0.12

Compiled with i686-w64-mingw32-g++ [i686-w64-mingw32]

Configured options: +pcre

Please see http://www.swig.org for reporting bugs and further information`

**Comment by Sqeaky** [comment]
This works for now, I am merging this with the understanding we will need a real solution as this is merged/split into Jagati packages.

**Pull request merged**
